=== Bainbridge-Growth/airbyte/airbyte-integrations/connectors/source-quickbooks-drivepoint/source_quickbooks_drivepoint/schemas/report.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "_Account": {
      "type": "string"
    },
    "_Account_id": {
      "type": "string"
    },
    "StartPeriod": {
      "type": "string"
    },
    "EndPeriod": {
      "type": "string"
    },
    "Currency": {
      "type": "string"
    },
    "ParentAccountName": {
      "type": "string"
    },
    "ParentAccountId": {
      "type": "string"
    },
    "GrandParentAccountName": {
      "type": "string"
    },
    "GrandParentAccountId": {
      "type": "string"
    },
    "CategoryAccountName": {
      "type": "string"
    },
    "CategoryAccountId": {
      "type": "string"
    },
    "Classification": {
      "type": "string"
    },
    "FullyQualifiedName": {
      "type": "string"
    },
    "AccountType": {
      "type": "string"
    },
    "FullAccountName": {
      "type": "string"
    },
    "Class": {
      "type": "string"
    },
    "Total_Money": {
      "type": "string"
    }
  }
}

=== Bainbridge-Growth/airbyte/airbyte-integrations/connectors/source-quickbooks-drivepoint/unit_tests/resources/expected_results/balance_sheet_nguyen_without_classes_20240423.json
[
{"_Account": "1072 Bill.com Money Out Clearing", "_Account_id": "100", "Total_Money": "0.00", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Bank Accounts", "ParentAccountId": "", "GrandParentAccountName": "Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Bank Accounts:1072 Bill.com Money Out Clearing"},
{"_Account": "Amazon Clearing", "_Account_id": "111", "Total_Money": "3276.42", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Bank Accounts", "ParentAccountId": "", "GrandParentAccountName": "Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Bank Accounts:Amazon Clearing"},
{"_Account": "Ampla Clearing", "_Account_id": "174", "Total_Money": "-15820.98", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Bank Accounts", "ParentAccountId": "", "GrandParentAccountName": "Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Bank Accounts:Ampla Clearing"},
{"_Account": "Candid Clearing", "_Account_id": "215", "Total_Money": "-14377.03", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Bank Accounts", "ParentAccountId": "", "GrandParentAccountName": "Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Bank Accounts:Candid Clearing"},
{"_Account": "Chase Checking (2622)", "_Account_id": "32", "Total_Money": "911498.40", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Bank Accounts", "ParentAccountId": "", "GrandParentAccountName": "Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Bank Accounts:Chase Checking (2622)"},
{"_Account": "Chase Savings (9317)", "_Account_id": "102", "Total_Money": "289909.03", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Bank Accounts", "ParentAccountId": "", "GrandParentAccountName": "Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Bank Accounts:Chase Savings (9317)"},
{"_Account": "PayPal", "_Account_id": "107", "Total_Money": "11447.73", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Bank Accounts", "ParentAccountId": "", "GrandParentAccountName": "Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Bank Accounts:PayPal"},
{"_Account": "Shopify Clearing", "_Account_id": "108", "Total_Money": "-39997.81", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Bank Accounts", "ParentAccountId": "", "GrandParentAccountName": "Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Bank Accounts:Shopify Clearing"},
{"_Account": "Accounts Receivable (A/R)", "_Account_id": "42", "Total_Money": "235889.87", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Accounts Receivable", "ParentAccountId": "", "GrandParentAccountName": "Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Accounts Receivable:Accounts Receivable (A/R)"},
{"_Account": "Due From Officers", "_Account_id": "172", "Total_Money": "26314.67", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Other Current Assets", "ParentAccountId": "", "GrandParentAccountName": "Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Other Current Assets:Due From Officers"},
{"_Account": "Inventory", "_Account_id": "30", "Total_Money": "1623585.37", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Inventory Asset", "ParentAccountId": "38", "GrandParentAccountName": "Other Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Other Current Assets:Inventory Asset:Inventory"},
{"_Account": "Prepaid Inventory", "_Account_id": "162", "Total_Money": "15157.33", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Inventory Asset", "ParentAccountId": "38", "GrandParentAccountName": "Other Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Other Current Assets:Inventory Asset:Prepaid Inventory"},
{"_Account": "Other Receivables", "_Account_id": "224", "Total_Money": "0.00", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Other Current Assets", "ParentAccountId": "", "GrandParentAccountName": "Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Other Current Assets:Other Receivables"},
{"_Account": "Prepaid Expenses", "_Account_id": "175", "Total_Money": "8624.15", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Other Current Assets", "ParentAccountId": "", "GrandParentAccountName": "Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Other Current Assets:Prepaid Expenses"},
{"_Account": "Undeposited Funds", "_Account_id": "43", "Total_Money": "0.00", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Other Current Assets", "ParentAccountId": "", "GrandParentAccountName": "Current Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Current Assets:Other Current Assets:Undeposited Funds"},
{"_Account": "Computer & Equipment", "_Account_id": "148", "Total_Money": "16062.52", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Fixed Assets", "ParentAccountId": "", "GrandParentAccountName": "ASSETS", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Fixed Assets:Computer & Equipment"},
{"_Account": "Depreciation", "_Account_id": "150", "Total_Money": "-15133.73", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Computer & Equipment", "ParentAccountId": "148", "GrandParentAccountName": "Fixed Assets", "GrandParentAccountId": "", "CategoryAccountName": "ASSETS", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "ASSETS:Fixed Assets:Computer & Equipment:Depreciation"},
{"_Account": "Accounts Payable (A/P)", "_Account_id": "103", "Total_Money": "240589.66", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Accounts Payable", "ParentAccountId": "", "GrandParentAccountName": "Current Liabilities", "GrandParentAccountId": "", "CategoryAccountName": "LIABILITIES AND EQUITY", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "LIABILITIES AND EQUITY:Liabilities:Current Liabilities:Accounts Payable:Accounts Payable (A/P)"},
{"_Account": "Amex Business (1000)", "_Account_id": "220", "Total_Money": "13489.79", "StartPeriod": "2024-03-01", "EndPeriod": "2024-03-30", "Currency": "USD", "ParentAccountName": "Credit Cards", "ParentAccountId": "", "GrandParentAccountName": "Current Liabilities", "GrandParentAccountId": "", "CategoryAccountName": "LIABILITIES AND EQUITY", "CategoryAccountId": "", "Classification": "", "FullyQualifiedName": "", "AccountType": "", "FullAccountName": "LIABILITIES AND EQUITY:Liabilities:Current Liabilities:Credit Cards:Amex Business (1000)"},
